Add docu for locales EN,DE
DENICeG/nastng-docs pull request #2
Opened 2021-11-11 13:46 UTC by bschoenbach

Neue Docu für den neuen NASTng

2021-12-03 08:40 UTC, doritr requested changes

2021-12-15 13:30 UTC, bschoenbach commented on docs/index.adoc
> +
solved

2021-12-15 13:32 UTC, bschoenbach commented on docs/index_de.adoc
> +verschiedenen Tests unterzogen, um sicherzustellen, dass sie korrekt konfiguriert sind und die Domain sicher
solved

2021-12-15 13:32 UTC, bschoenbach commented on docs/index_de.adoc
> +Service (bekannt als NASTng) wird in Abschnitt <<Anwendung>> beschrieben.
solved

2021-12-15 14:03 UTC, bschoenbach commented on docs/index_de.adoc
> +xref:nast/nast_de.adoc#NAST---Name-Server-Tester[Lernen Sie unseren NASTng Service kennen.]
accepted -> NameServer-Tester

2021-12-15 14:31 UTC, bschoenbach commented on docs/spec/dnssec_de.adoc
> +Zonengenerierung werden die entsprechenden DS-Records7 erzeugt (derzeit genau ein
accepted

2021-12-15 14:33 UTC, bschoenbach commented on docs/spec/dnssec_de.adoc
> +von maßgebender Bedeutung. Diese sind wiefolgt definiert:
accepted

2021-12-15 14:35 UTC, bschoenbach commented on docs/spec/dnssec_de.adoc
> +DNS abrufbaren Information angestellt.
accepted

2021-12-15 14:36 UTC, bschoenbach commented on docs/spec/dnssec_de.adoc
> +im Auftrag **MUSS** &le; 5 sein. Andernfalls erfolgt die Ausgabe eines entsprechenden **ERROR**.
accepted

2021-12-15 14:46 UTC, bschoenbach commented on docs/spec/dnssec_de.adoc
> +|===
Ja steht schon fest siehe https://www.denic.de/fileadmin/public/documentation/DENIC-26p.pdf Seite 21, ganz unten......heist aber nicht das wir es nicht ändern können......
deshalb: accepted

2021-12-15 14:47 UTC, bschoenbach commented on docs/spec/dnssec_de.adoc
> +Bit 7 (ZONE) **MUSS** gesetzt sein. Ssonst Ausgabe von **ERROR**.
? sehe keinen Unterschied...sollte so passen

2021-12-15 14:48 UTC, bschoenbach commented on docs/spec/dnssec_de.adoc
> +Bit 7 (ZONE) **MUSS** gesetzt sein. Ssonst Ausgabe von **ERROR**.
wie blöd von mir....jetzt seh ich es
accepted

2021-12-15 14:48 UTC, bschoenbach commented on docs/spec/dnssec_de.adoc
> +Anchor fungieren.
accepted

2021-12-15 14:51 UTC, bschoenbach commented on docs/spec/dnssec_de.adoc
> +Dieses Feld soll den KSK im DNSKEY-RRSet identifizieren. Es entspricht guter Praxis, es
Nö ...."Best Practice" klingt gut.
accepted

2021-12-15 14:55 UTC, bschoenbach commented on docs/spec/dnssec_de.adoc
> +zwingend vorgeschrieben und wird somit statisch angenommen. Es erfolgt daher keine Issue-Ausgabe bei Verstoß.
-> Es erfolgt daher weder eine WARNING noch ein ERROR bei Verstoß.... auch ok?

2021-12-15 15:06 UTC, bschoenbach commented on docs/spec/dnssec_de.adoc
> +Der Exponent *MUSS* &le; 128 Bit lang sein. Sonst Ausgabe von **ERROR**.
passt so weil &le; wird zu ≤ beim erzeugen der docu.
obsolete

2021-12-15 15:10 UTC, bschoenbach commented on docs/spec/dnssec_de.adoc
> +im Auftrag **MUSS** &le; 5 sein. Andernfalls erfolgt die Ausgabe eines entsprechenden **ERROR**.
passt so weil `&le;` wird zu ≤ beim erzeugen der docu.
obsolete

2021-12-15 15:13 UTC, bschoenbach commented on docs/spec/dnssec_de.adoc
> +Für die DSA basierten Algorithmen 3 und 6 gilt folgendes.
accepted

2021-12-15 15:16 UTC, bschoenbach commented on docs/spec/dnssec_de.adoc
> +| No visible DNSKEY found in signing directly or indirectly the SOA RR obtained in response
? müssen wir nochmal checken...found in signing directly or indirectly of the SOA RR ...hat für mich eine andere bedeutung
war bisher auch so in der alten Docu sihe Seite 22, mitte
https://www.denic.de/fileadmin/public/documentation/DENIC-26p.pdf

2021-12-15 15:17 UTC, bschoenbach commented on docs/spec/dnssec_de.adoc
> +verhindert Security Lameness. Die Validierung ist auf die delegierte Zone beschränkt damit
accepted

2021-12-16 05:57 UTC, bschoenbach commented on docs/spec/dnssec_de.adoc
> +an die autoritativen Server bzw. die sie umgebende Infrastruktur.
accepted

2021-12-16 06:03 UTC, bschoenbach commented on docs/spec/dnssec_de.adoc
> +Paketgröße und Vefügbarkeit unterstützen. Andernfalls erfolgt die Ausgabe einer entsprechenden
accepted

2021-12-16 06:07 UTC, bschoenbach commented on docs/spec/dnssec_de.adoc
> +| Querying some authoritative nameservers via EDNS0 UDP yields truncation because of not supporting sufficient packet size.
yields kommt leider mehrfach konsistent in verwandten Fehlermeldungen vor...sorry

2021-12-16 06:09 UTC, bschoenbach commented on docs/spec/dnssec_de.adoc
> +| Querying some authoritative nameservers via EDNS0 UDP yields unreachable
yields kommt leider mehrfach konsistent in verwandten Fehlermeldungen vor...sorry

2021-12-16 06:09 UTC, bschoenbach commented on docs/spec/dnssec_de.adoc
> +| Querying some authoritative nameservers via EDNS0 UDP yields timeout
yields kommt leider mehrfach konsistent in verwandten Fehlermeldungen vor...sorry

2021-12-16 06:12 UTC, bschoenbach commented on docs/spec/dnssec.adoc
> +security data (i.e. keys) needs to be provided within the corresponding zones.
accepted

2021-12-16 06:14 UTC, bschoenbach commented on docs/spec/dnssec.adoc
> +This key is placed within DNSKEY-RRSet of the delegated zone which is signed by the key, too.
accepted

2021-12-16 06:16 UTC, bschoenbach commented on docs/spec/dnssec.adoc
> +
accepted

2021-12-16 06:19 UTC, bschoenbach commented on docs/spec/dnssec.adoc
> +all signatures and DS-RRs are generated for each KSK automatically and distributed
accepted

2021-12-16 06:21 UTC, bschoenbach commented on docs/spec/dnssec.adoc
> +
accepted

2021-12-16 06:22 UTC, bschoenbach commented on docs/spec/dnssec.adoc
> +between Zone Signing Key (ZSK) and Key Signing Key (KSK). While ZSK is used to sign any record
accepted

2021-12-16 06:30 UTC, bschoenbach commented on docs/spec/dnssec.adoc
> +
accepted

2021-12-16 06:31 UTC, bschoenbach commented on docs/spec/dnssec.adoc
> +
Es soll gedagt werden: Ein im Auftrag übergebener DNSKEY-RR ist sichtbar, wenn er im DNSKEY-RRSet der delegierten Zone
enthalten ist.

2021-12-16 06:32 UTC, bschoenbach commented on docs/spec/dnssec.adoc
> +
accepted

2021-12-16 06:33 UTC, bschoenbach commented on docs/spec/dnssec.adoc
> +
accepted

2021-12-16 06:36 UTC, bschoenbach commented on docs/spec/dnssec.adoc
> +
accepted.

2021-12-16 06:36 UTC, bschoenbach commented on docs/spec/dnssec.adoc
> +
accepted

2021-12-16 06:38 UTC, bschoenbach commented on docs/spec/dnssec.adoc
> +
alternativ: Bit 8 (REVOKE) **MUST** be cleared.......so sagen es IT-ler/Informatiker.

2021-12-16 06:40 UTC, bschoenbach commented on docs/spec/dnssec.adoc
> +Bit 15 (SEP) **SHOULD** be SET. Otherwise a **WARNING** is issued.
accepted

2021-12-16 06:42 UTC, bschoenbach commented on docs/spec/dnssec.adoc
> +of https://www.iana.org/assignments/dns-sec-alg-numbers/dns-sec-alg-numbers.xhtml[IANA-Registry].
accepted

2021-12-16 06:43 UTC, bschoenbach commented on docs/spec/dnssec.adoc
> +The public key field **MUST** cover the base64 encoded key value. Otherwise **ERROR**.
haben uns auf base64 in englisch und Base64 in deutsch konsolidiert.

2021-12-16 06:44 UTC, bschoenbach commented on docs/spec/dnssec.adoc
> +
accepted

2021-12-16 06:51 UTC, bschoenbach commented on docs/spec/dnssec.adoc
> +
accepted.  für EN: (DNSKEY-RR -> DNSKEY RR, DNSKEY-RRSet -> DNSKEY RRset )

2021-12-16 06:52 UTC, bschoenbach commented on docs/spec/dnssec.adoc
> +Otherwise **ERROR**.
accepted

2021-12-16 06:53 UTC, bschoenbach commented on docs/spec/dnssec.adoc
> +
accepted

2021-12-16 06:56 UTC, bschoenbach commented on docs/spec/dnssec.adoc
> +is assumed but not tested explicitly. This allows online signing for DSA and ECDSA based
accepted

2021-12-16 06:57 UTC, bschoenbach commented on docs/spec/dnssec.adoc
> +At least one visible DNSKEY-RR of request **MUST** validate the signature of the DNSKEY-RRSet.
accepted

2021-12-16 06:57 UTC, bschoenbach commented on docs/spec/dnssec.adoc
> +This requirements enforces named proof of possession of section <<Validation Concept>>.
accepted

2021-12-16 07:00 UTC, bschoenbach commented on docs/spec/dnssec.adoc
> +visible DNSKEY-RR of request or within DNSKEY-RRSet must validate the signature of the SOA-RR.
accepted

2021-12-16 07:01 UTC, bschoenbach commented on docs/spec/dnssec.adoc
> +and prevents security lameness. Trust validation is limited to delegated zone level to allow
accepted

2021-12-16 07:02 UTC, bschoenbach commented on docs/spec/dnssec.adoc
> +
accepted

2021-12-16 07:04 UTC, bschoenbach commented on docs/spec/dnssec.adoc
> +**MUST** respond with DNSSEC data (i.e signatures) towards DO-Bit signed querries.
accepted

2021-12-16 07:08 UTC, bschoenbach commented on docs/spec/dnssec.adoc
> +package size and connectivity. Otherwise a corresponding **WARNING** is issued.
accepted

2021-12-16 07:09 UTC, bschoenbach commented on docs/spec/dnssec.adoc
> +
wie bereits erwähnt....yields wird konform in anderen Messages bereits verwendet

2021-12-16 07:09 UTC, bschoenbach commented on docs/spec/dnssec.adoc
> +| Querying some authoritative nameservers via EDNS0 UDP yields timeout
wie bereits erwähnt....yields wird konform in anderen Messages bereits verwendet

2021-12-16 07:09 UTC, bschoenbach commented on docs/spec/dnssec.adoc
> +|===
wie bereits erwähnt....yields wird konform in anderen Messages bereits verwendet

2021-12-16 07:10 UTC, bschoenbach commented on docs/spec/dnssec.adoc
> +
accepted

2021-12-16 07:39 UTC, bschoenbach commented on docs/spec/general.adoc
> +Different issue types (i.e warning, error) are used to describe violations within
nope....ein result ist was anderes (das große ganze am schluss einer prüfng welches issues unterschiedlichen typs (warnings und oder errors) und zusätzliche Informationen beinhalten kann (Debug Infos)).

2021-12-16 07:41 UTC, bschoenbach commented on docs/spec/general.adoc
> +requirement and issues type is defined as follows:
nope....ein result ist was anderes (das große ganze am schluss einer prüfng welches issues unterschiedlichen typs (warnings und oder errors) und zusätzliche Informationen beinhalten kann (Debug Infos)).
Alternativ könnte man über issue levels nachdenken....

2021-12-16 07:41 UTC, bschoenbach commented on docs/spec/general.adoc
> +This issue covers the violation of a requirement that **SHOULD** be fullfilled.
nope....ein result ist was anderes (das große ganze am schluss einer prüfng welches issues unterschiedlichen typs (warnings und oder errors) und zusätzliche Informationen beinhalten kann (Debug Infos)).
Alternativ könnte man über issue levels nachdenken....

2021-12-16 07:42 UTC, bschoenbach commented on docs/spec/general.adoc
> +affect the overall result of predelegation check themselves.
accepted

2021-12-16 07:42 UTC, bschoenbach commented on docs/spec/general.adoc
> +This issue covers the violation of a requirement that ** MUST ** be fullfilled.
nope....ein result ist was anderes (das große ganze am schluss einer prüfng welches issues unterschiedlichen typs (warnings und oder errors) und zusätzliche Informationen beinhalten kann (Debug Infos)). Alternativ könnte man über issue levels nachdenken....

2021-12-16 07:43 UTC, bschoenbach commented on docs/spec/general.adoc
> +final zone delegation of the requested domain. This is necessary because namesevers can
accepted

2021-12-16 07:44 UTC, bschoenbach commented on docs/spec/general.adoc
> +be opareted by any uncontracted third party (i.e. none-members) of Denic e.G.. Additional
accepted

2021-12-16 07:48 UTC, bschoenbach commented on docs/spec/general.adoc
> +| Insufficient diversity of nameserver' s IP addresses
nope hier ist ein spezifischer nameserver gemeint

2021-12-16 07:49 UTC, bschoenbach commented on docs/spec/general.adoc
> +| Insufficient diversity of nameserver' s IPv4 addresses
nope hier ist ein spezifischer nameserver gemeint

2021-12-16 07:50 UTC, bschoenbach commented on docs/spec/general.adoc
> +be delegable by a two-leveled redundancy setup by at least two different nameservers
accepted

2021-12-16 07:52 UTC, bschoenbach commented on docs/spec/general.adoc
> +Predelegation check uses narrow glue policy. Hence, glue-records need to be available in .de zone
accepted

2021-12-16 07:53 UTC, bschoenbach commented on docs/spec/general.adoc
> +At least one IP address (i.e. IPv4 or IPv6) **MUST** be specified in check request for any nameserver
accepted

2021-12-16 07:54 UTC, bschoenbach commented on docs/spec/general.adoc
> +Considering both addressing cases IPv4 and IPv6 at least one glue-record is required.
accepted

2021-12-16 07:54 UTC, bschoenbach commented on docs/spec/general.adoc
> +None IP address (i.e. IPv4 or IPv6) **SHOULD** be specified in check request for any nameserver
accepted

2021-12-16 07:58 UTC, bschoenbach commented on docs/spec/general.adoc
> +Because narrow glue policy is used just glue records (i.e. A, AAAA) of zone located nameservers are allowed.
accepted (also dein Vorschlag)

2021-12-16 08:00 UTC, bschoenbach commented on docs/spec/general.adoc
> +For each specified IP address of any nameserver in check request the corresponding A- and AAAA-RRset **MUST**
accepted

2021-12-16 08:03 UTC, bschoenbach commented on docs/spec/general.adoc
> +**Further explanation:** Since glue-records as well as authoritative data coexist in DNS both need
accepted

2021-12-16 08:03 UTC, bschoenbach commented on docs/spec/general.adoc
> +(e.g. missing IPs in glue-records).
accepted

2021-12-16 08:04 UTC, bschoenbach commented on docs/spec/general.adoc
> +| Refresh value ot of range
accepted

2021-12-16 08:06 UTC, bschoenbach commented on docs/spec/general.adoc
> +On the opposite, high rates will lead to more unupdated data. Therefore, any violation results in warning
accepted (outdated data)

2021-12-16 08:06 UTC, bschoenbach commented on docs/spec/general.adoc
> +because the setting gets defined by the nameserver operators.
accepted

2021-12-16 08:07 UTC, bschoenbach commented on docs/spec/general.adoc
> +This value overrules the refresh value if SOA sync between nameservers failed and will continue until sync
accepted

2021-12-16 08:07 UTC, bschoenbach commented on docs/spec/general.adoc
> +is achieved or expiry threshold is reached. Hence the value needs to be lower than <<Refresh>>. Keep in mind that
accepted

2021-12-16 08:09 UTC, bschoenbach commented on docs/spec/general.adoc
> +The NS-RRset of the delegated zone **MUST** match the request's nameserver list completely.
accepted

2021-12-16 08:11 UTC, bschoenbach commented on docs/spec/general.adoc
> +The delegated zone **MUST** be free of any CNAME-RR. Otherwise **ERROR**.
accepted (kein Bezug im ERROR weil es sich auf die SOA Anfrage bezieht)

2021-12-16 08:12 UTC, bschoenbach commented on docs/spec/general.adoc
> +large QNAMEs, all adddress entries and glue-records). Otherwise **ERROR**.
accepted

2021-12-16 08:15 UTC, bschoenbach commented on docs/spec/general.adoc
> +avoid high workloads of TCP based fallback retries due to truncation of former UDP requests.
accepted

2021-12-16 08:16 UTC, bschoenbach commented on docs/spec/general.adoc
> +the SOA-RR of any related nameserver. Otherwise **WARNING**.
accepted

2021-12-16 08:16 UTC, bschoenbach commented on docs/spec/general.adoc
> +address scope, allocated and routable. Any violation results in corresponding **ERROR** below.
accepted

2021-12-16 08:17 UTC, bschoenbach commented on docs/spec/general.adoc
> +**WARNING** will be issued.
accepted

2021-12-16 08:17 UTC, bschoenbach commented on docs/spec/general.adoc
> +a switch over to TCP could be possible as mentioned in https://www.ietf.org/rfc/rfc123.txt[RFC123].
accepted

2021-12-16 08:21 UTC, bschoenbach commented on docs/spec/general_de.adoc
> +Der Predelagation Check verwendet verschiedene Issue-Typen (d.h. WARNING, ERROR) um Verstöße
wie auch schon im englischen angemerkt......ein Result ist was größeres...ein Issue hat einen Code, einen Typen (aka Severity Level), eine Message (Erläuterunsgtext) und optionale Argumente (z.B. IP Adresse, Protokoll etc )

2021-12-16 08:22 UTC, bschoenbach commented on docs/spec/general_de.adoc
> +führt zur Ausgabe eins **ERROR** welcher das Check-Gesamtergebnis letztlich negativ
accepted

2021-12-16 08:23 UTC, bschoenbach commented on docs/spec/general_de.adoc
> +Empfehlungen werden mit **SOLL** beschrieben, ein Verstoß führt zur Ausgabe einer **WARNING**
accepted

2021-12-16 08:26 UTC, bschoenbach commented on docs/spec/general_de.adoc
> +autoritativ sein. Sonst Ausgabe von **ERROR**.
accepted

2021-12-16 08:28 UTC, bschoenbach commented on docs/spec/general_de.adoc
> +Einverständnis mit dieser Delegation unterstellt, wenn die Zone autoritativ bedient wird.
accepted

2021-12-16 08:31 UTC, bschoenbach commented on docs/spec/general_de.adoc
> +Andernfals erfolgt enstrepchend die Ausgabe folgender **ERROR**.
accepted

2021-12-16 08:32 UTC, bschoenbach commented on docs/spec/general_de.adoc
> +| Insufficient diversity of nameserver' s IP addresses
nope ...wie auch im englischen angemerkt....es handelt sich um einen spezifischen nameserver ....keine Mehrzahl

2021-12-16 08:32 UTC, bschoenbach commented on docs/spec/general_de.adoc
> +| Insufficient diversity of nameserver' s IPv4 addresses
nope ...wie auch im englischen angemerkt....es handelt sich um einen spezifischen nameserver ....keine Mehrzahl
obsolete

2021-12-16 08:33 UTC, bschoenbach commented on docs/spec/general_de.adoc
> +oder mehrere Records gleichen Typs4) immer vollständig anzugeben, nicht etwa nur
accepted

2021-12-16 08:33 UTC, bschoenbach commented on docs/spec/general_de.adoc
> +ausgegangen werden kann, dass nicht ignoriert werden sollte.
accepted

2021-12-16 08:34 UTC, bschoenbach commented on docs/spec/general_de.adoc
> +Das NS-RRSet **MUSSS** exakt mit der im Auftrag angegebenen Liste der Nameserver
accepted

2021-12-16 08:34 UTC, bschoenbach commented on docs/spec/general_de.adoc
> +Die Angabe des Primary Nameservers im SOA -RR der beantragten Zone **SOLL** auf allen
accepted

2021-12-16 08:36 UTC, bschoenbach commented on docs/spec/glossary.adoc
> +=== Issues
müssen wir nochmal gemeinsam mit P. Koch klären

2022-01-18 14:21 UTC, bschoenbach commented on docs/spec/general_de.adoc
> +Der Predelagation Check verwendet verschiedene Issue-Typen (d.h. WARNING, ERROR) um Verstöße
Issue-Typen lassen wegen naming convention für Result als Check-Ergebnis

2022-01-18 14:29 UTC, bschoenbach commented on docs/spec/dnssec_de.adoc
> +| No visible DNSKEY found in signing directly or indirectly the SOA RR obtained in response
bleibt so

2022-01-18 14:31 UTC, bschoenbach commented on docs/spec/dnssec_de.adoc
> +| Querying some authoritative nameservers via EDNS0 UDP yields truncation because of not supporting sufficient packet size.
yields -> causes

2022-01-18 14:32 UTC, bschoenbach commented on docs/spec/dnssec_de.adoc
> +| Querying some authoritative nameservers via EDNS0 UDP yields timeout
yields -> causes

2022-01-18 14:34 UTC, bschoenbach commented on docs/spec/dnssec_de.adoc
> +| Querying some authoritative nameservers via EDNS0 UDP yields unreachable
yields -> causes

2022-01-18 14:34 UTC, bschoenbach commented on docs/spec/dnssec.adoc
> +
siehe deutsch

2022-01-18 14:34 UTC, bschoenbach commented on docs/spec/dnssec.adoc
> +| Querying some authoritative nameservers via EDNS0 UDP yields timeout
siehe deutsch

2022-01-18 14:35 UTC, bschoenbach commented on docs/spec/dnssec.adoc
> +|===
siehe deutsch

2022-01-18 14:48 UTC, bschoenbach commented on docs/spec/dnssec_de.adoc
> +zwingend vorgeschrieben und wird somit statisch angenommen. Es erfolgt daher keine Issue-Ausgabe bei Verstoß.
Es erfolgt daher weder eine **WARNING** noch ein **ERROR**
bei Verstoß, wenn dieser Wert nicht gesetzt ist.

2022-01-18 15:11 UTC, merged